### ISSUE TITLE
use local llm to generate but it doesn't work... 

### ISSUE THREAD

**Issue by loredunk** [rjk-git/self-cognition-instuctions#1]
this is my enviroment set:
openai                            1.40.2

```(llamafac) gavin@gavin-System-Product-Name:~/workspace/self-cognition-instuctions$ python generate.py 
Generating self cognition data:   0%|                                                    | 0/100 [00:00<?, ?it/s]

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

Traceback (most recent call last):
  File "/home/gavin/workspace/self-cognition-instuctions/generate.py", line 39, in main
    chat_completion = openai.ChatCompletion.create(
  File "/home/gavin/miniconda3/envs/llamafac/lib/python3.10/site-packages/openai/lib/_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742


Generating self cognition data:   0%|                                                    | 0/100 [00:00<?, ?it/s]

```

**Comment by rjk-git** [comment]
You can modify the part that calls the OpenAI API yourself, as the version used in the repository may no longer be supported.

**Comment by loredunk** [comment]
> You can modify the part that calls the OpenAI API yourself, as the version used in the repository may no longer be supported.

got it
